name: scrips_core
description: Simplifying the use of both Material and Cupertino widgets with a single widget
version: 1.0.0
author: Suvankar Das <suv.das19@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  flare_splash_screen:
  dio:
  rflutter_alert:
  get_it:
  localstorage:
  json_serializable:
  scoped_model:
  flutter_platform_widgets:
  date_range_picker:
    path: ../third-party/date_range_picker-master
  scrips_shared_features:
    path: ../scrips_shared_features
  flutter_svg:
  flutter_typeahead_web:
  dartz:
  equatable:
  flutter_tags:
  flutter_bloc:
  shared_preferences:
  extended_tabs:
  image_cropper:
  csv:
  charts_flutter:
  file_picker:
  reorderables:
  feature_discovery:
    path: ../third-party/feature_discovery-master
  country_pickers:
dev_dependencies:
  build_runner:

dependency_overrides:
  intl: 0.17.0
  path: ^1.8.0
  clock: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/growth_graph_data/

  # To add assets to your package, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
          weight: 900
    - family: Scrips
      fonts:
        - asset: assets/fonts/Scrips/Scrips.ttf


